var index =
[
    [ "Project README", "index.html#main_project_readme", null ],
    [ "Getting Started Fast", "index.html#main_getting_started", null ],
    [ "Navigating The Documentation", "index.html#main_documentation_structure", null ],
    [ "Build Status", "index.html#main_build_status", null ],
    [ "QB Framework: Introduction", "introduction_readme.html", null ],
    [ "QB Framework: A High-Performance C++ Actor Toolkit", "intro_overview_md.html", null ],
    [ "QB Framework Philosophy: Building Modern C++ Systems", "intro_philosophy_md.html", null ],
    [ "QB Framework: Core Concepts", "core_concepts_readme.html", null ],
    [ "Core Concept: The Actor Model in QB", "core_concepts_actor_model_md.html", null ],
    [ "Core Concept: The QB Event System", "core_concepts_event_system_md.html", null ],
    [ "Core Concept: Asynchronous I/O Model in QB", "core_concepts_async_io_md.html", null ],
    [ "Core Concept: Concurrency &amp; Parallelism in QB", "core_concepts_concurrency_md.html", null ],
    [ "QB-IO Module: High-Performance Asynchronous I/O &amp; Utilities", "qb_io_readme_md.html", null ],
    [ "QB-IO: Feature Showcase", "qb_io_features_md.html", null ],
    [ "QB-IO: The Asynchronous Engine (`qbio::async`)", "qb_io_async_system_md.html", null ],
    [ "QB-IO: Understanding Transports", "qb_io_transports_md.html", null ],
    [ "QB-IO: Framing Messages with Protocols", "qb_io_protocols_md.html", null ],
    [ "QB-IO: Secure TCP with SSL/TLS", "qb_io_ssl_transport_md.html", null ],
    [ "QB-IO: Essential Utilities &amp; Helpers", "qb_io_utilities_md.html", null ],
    [ "QB-Core Module: The Actor Engine", "qb_core_readme_md.html", null ],
    [ "QB-Core: Key Features &amp; Capabilities", "qb_core_features_md.html", null ],
    [ "QB-Core: Mastering `qbActor`", "qb_core_actor_md.html", null ],
    [ "QB-Core: Event Messaging Between Actors", "qb_core_messaging_md.html", null ],
    [ "QB-Core: Engine - `qbMain` &amp; `VirtualCore`", "qb_core_engine_md.html", null ],
    [ "QB-Core: Common Actor Patterns &amp; Utilities", "qb_core_patterns_md.html", null ],
    [ "QB Framework: Integrating Core Actors with Asynchronous I/O", "core_io_integration_readme_md.html", null ],
    [ "Integrating Core &amp; IO: Asynchronous Operations within Actors", "core_io_async_in_actors_md.html", null ],
    [ "QB &amp; IO: Building Network-Enabled Actors", "core_io_network_actors_md.html", null ],
    [ "Case Studies: QB Core &amp; IO Integration Examples", "core_io_example_analyses_readme.html", null ],
    [ "Case Study: Building a TCP Chat System with QB Actors", "example_analysis_chat_tcp_md.html", null ],
    [ "Case Study: Simulating Distributed Computing with QB Actors", "example_analysis_dist_comp_md.html", null ],
    [ "Case Study: Building a File System Monitor with QB Actors", "example_analysis_file_monitor_md.html", null ],
    [ "Case Study: Asynchronous File Processing with Manager-Worker Actors", "example_analysis_file_processor_md.html", null ],
    [ "Case Study: A Publish/Subscribe Message Broker with QB Actors", "example_analysis_msg_broker_md.html", null ],
    [ "QB Framework: Developer Guides", "guides_readme.html", null ],
    [ "Getting Started with the QB Actor Framework", "guides_getting_started_md.html", null ],
    [ "QB Actor Framework: Design Patterns Cookbook", "guides_patterns_cookbook_md.html", null ],
    [ "QB Framework: Advanced Techniques &amp; System Design", "guides_advanced_usage_md.html", null ],
    [ "QB Framework: Performance Tuning Guide", "guides_performance_tuning_md.html", null ],
    [ "QB Framework: Error Handling &amp; Resilience Strategies", "guides_error_handling_md.html", null ],
    [ "QB Framework: Effective Resource Management", "guides_resource_management_md.html", null ],
    [ "QB Framework: Reference Documentation", "reference_readme.html", null ],
    [ "QB Framework: Detailed API Overview", "ref_api_overview_md.html", null ],
    [ "Reference: Building the QB Actor Framework", "ref_building_md.html", null ],
    [ "Reference: Testing the QB Actor Framework", "ref_testing_md.html", null ],
    [ "QB Actor Framework: Frequently Asked Questions (FAQ)", "ref_faq_md.html", null ],
    [ "QB Actor Framework: Glossary of Terms", "ref_glossary_md.html", null ],
    [ "QB Framework: Lock-Free Primitives Reference", "ref_lockfree_primitives_md.html", null ]
];