/**
 * @file qb/io/async/event/disconnected.h
 * @brief Disconnection event for asynchronous I/O operations.
 *
 * This file defines the disconnected event structure which is triggered
 * when an I/O connection is closed or lost. The derived classes can handle
 * this event by implementing the `void on(disconnected &&)` method.
 *
 * @author qb - C++ Actor Framework
 * @copyright Copyright (c) 2011-2025 qb - isndev (cpp.actor)
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * @ingroup AsyncEvent
 */

#ifndef QB_IO_ASYNC_EVENT_DISCONNECTED_H
#define QB_IO_ASYNC_EVENT_DISCONNECTED_H

#include <system_error>
#include <string>

namespace qb::io::async::event {

/**
 * @struct disconnected
 * @ingroup AsyncEvent
 * @brief Event triggered when a connection is closed or lost.
 *
 * This event is passed to the derived class's `on()` method when
 * a disconnection occurs in an I/O object (e.g., a TCP session).
 * The `reason` field can contain a code indicating the cause of disconnection.
 * Additional error information is available via `error_code` and `message` fields.
 *
 * Usage Example:
 * @code
 * class MyNetworkHandler : public qb::io::async::io<MyNetworkHandler> { // Or similar base
 * public:
 *   // ... other methods ...
 *   void on(qb::io::async::event::disconnected &&event) {
 *     if (event.reason == 0 && !event.error_code) {
 *       // Normal disconnection by peer or self
 *       LOG_INFO("Connection closed normally.");
 *     } else {
 *       // Disconnection due to an error
 *       if (event.error_code) {
 *         LOG_WARN("Connection lost: " << event.error_code.message());
 *       } else if (!event.message.empty()) {
 *         LOG_WARN("Connection lost: " << event.message);
 *       } else {
 *         LOG_WARN("Connection lost, reason: " << event.reason);
 *       }
 *     }
 *     // Perform cleanup, attempt reconnection, etc.
 *   }
 * };
 * @endcode
 */
struct disconnected {
    int reason = 0; /**< Reason code for the disconnection. Common values:
                       * - `0`: Normal shutdown (peer closed connection or graceful disconnect)
                       * - `1`: User-initiated disconnect (default when calling `disconnect()`)
                       * - `> 0`: Reserved for application-specific use (e.g., `qbm-http` uses 0-5 for its `DisconnectedReason` enum)
                       * - `-1`: Protocol error (protocol marked as invalid via `not_ok()`) - automatic from `qb-io`
                       * - `-2`: Message too large (DoS protection - message exceeded `max_message_size()`) - automatic from `qb-io`
                       * - `-3`: Buffer size limit exceeded (DoS protection - read/write buffer exceeded `max_read_buffer_size()` or `max_write_buffer_size()`) - automatic from `qb-io`
                       * Negative values are reserved for automatic error codes generated by `qb-io`.
                       * Positive values (> 0) can be used by applications (like `qbm-http`) for their own reason codes.
                       * Non-zero positive values often correspond to application-specific or system error codes (errno)
                       * if the disconnection was due to an error detected by the underlying transport or OS. */
    
    std::error_code error_code{}; /**< Optional system error code providing detailed error information.
                                    * Set when a system-level error occurs (e.g., from errno or socket errors).
                                    * Empty (default-constructed) if no system error code is available. */
    
    std::string message{}; /**< Optional human-readable error message providing additional context
                             * about the disconnection. Empty if no message is available. */
    
    /**
     * @brief Creates a disconnected event with system error information.
     * @param reason_code The reason code for disconnection.
     * @param system_error The system error code (from errno or socket errors).
     * @param error_message Optional human-readable error message.
     * @return A disconnected event with error information populated.
     */
    static disconnected
    with_error(int reason_code, int system_error, std::string const &error_message = {}) {
        disconnected evt;
        evt.reason = reason_code;
        if (system_error != 0) {
            evt.error_code = std::error_code(system_error, std::system_category());
        }
        if (!error_message.empty()) {
            evt.message = error_message;
        }
        return evt;
    }
    
    /**
     * @brief Creates a disconnected event with system error information from errno.
     * @param reason_code The reason code for disconnection.
     * @param error_message Optional human-readable error message.
     * @return A disconnected event with error information populated.
     */
    static disconnected
    with_system_error(int reason_code, std::string const &error_message = {}) {
        return with_error(reason_code, errno, error_message);
    }
};

} // namespace qb::io::async::event

#endif // QB_IO_ASYNC_EVENT_DISCONNECTED_H
